### ISSUE TITLE
Error python al descargar la VPN obtengo error: ImportError: No module named requests

### ISSUE THREAD

**Issue by irraz** [s4vitar/htbExplorer#2]
Buenas!

No he conseguido resolver la dependencia "requests" de python, ya que dice que esta instalada:
pip install requests
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.23.0)

Cuando ejecuto por primera vez el htbExplorer para descargar la vpn esto es lo que obtengo:

sudo ./htbExplorer -v irraz.ovpn
[sudo] password for irraz: 

[X] html2text is not installed
[i] Installing...
[V] html2text installed                                                         
[X] jq is not installed                                                                
[i] Installing...                                                                         
[V] jq installed

[*] You need to login first...

Traceback (most recent call last):
  File "downloadVPN.py", line 6, in <module>
    import requests, re, getpass, urllib3, sys
ImportError: No module named requests

[V] The VPN has been download successfuly

**Comment by irraz** [comment]
Pues he dado muchas vueltas, y nada no sé dónde esta el problema...

Para aportar más información esto me ocurre tanto en kali como en una parrot recien instalada:

└──╼ $cat /etc/lsb-release 
DISTRIB_ID=Parrot
DISTRIB_RELEASE=4.10
DISTRIB_CODENAME=rolling
DISTRIB_DESCRIPTION="Parrot 4.10"

**Comment by hugocornago** [comment]
Tienes que instalar el modulo requests para python.
Usa: $ python3 -m pip install requests
Si te da un error de permisos usa sudo.

Si te vuelve a pasar te recomiendo que antes de reportar aqui busques un poco en google: https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests

Espero que te sirva :)

**Comment by irraz** [comment]
Hola @hugocornago te agradezco la respuesta, pero tanto en kali como en Parrot tengo instalado request, de hecho viene instalado por defecto en ambas. 

De hecho lo pongo al principio:

pip install requests
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.23.0)

Si te fijas me devuelve que ya esta instalado para python3, y de ahí mi duda.

Muchas gracias,

**Comment by irraz** [comment]
Al final mi problema era que el script necesita instalar pip para python2 en parrot no viene por defecto, y por lo tanto las dependencias de requests etc se instalan para python3 y no funcionan.  Resuelto eso el script funciona con -v para descargar el openvpn, pero si tienes el doble factor habilitado en htb no funciona. Cierro esto.
